# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
 - group: 'DotnetCoreVersion'
 - name: 'buildConfiguration'
   value: 'Release'
 - name: 'version'
   value: '0.1.1'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.2.0'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(netCoreVersion)'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration) --no-build
  displayName: 'dotnet test $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/CSVToESLib.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: byEnvVar
    versionEnvVar: version
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Angrist Nuget'